### Read all users
GET http://localhost:4000/user-api/users


### request for proteced roture
GET http://localhost:4000/user-api/test


### Create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"samp",
    "password":"samp",
    "age":20
}



### user authenticatoin request
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username":"samp",
    "password":"samp"
}



###raed user by object id
GET http://localhost:4000/user-api/users/697dba9f7f755dfb20b4aa99


### update user
PUT http://localhost:4000/user-api/users/697dbc6db9462d847725ce6a
Content-Type: application/json

{
    "username":"sai",
    "password":"sai",
    "age":20
}


### delete user by id
DELETE http://localhost:4000/user-api/users/698058ede24d5ac461fdbf89






### get all products data
GET http://localhost:4000/product-api/products

###add new products
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid":123,
    "productName":"book",
    "price":150
}


###  get produxt by id
GET http://localhost:4000/product-api/products/697dd39b4a10f049203935e3



### get product by id
PUT http://localhost:4000/product-api/products/697dd39b4a10f049203935e3
Content-Type: application/json

{
    "pid":123,
    "productName":"book",
    "price":200
}
